#. Common {{{
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
#. }}}

#. Edit plugins {{{
[[plugins]]
repo = 'thinca/vim-zenspace'
hook_add = '''
  au MyAutoCmd ColorScheme * highlight ZenSpace ctermfg=LightGray guibg=DarkGray
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
on_cmd = [
    'Git', 'Gcd', 'Glcd', 'Gstatus', 'Gcommit', 'Gmerge',
    'Gpull', 'Gpush', 'Gfetch', 'Ggrep', 'Glgrep', 'Glog',
    'Gllog', 'Gedit', 'Gsplit', 'Gvsplit', 'Gtabedit', 'Gpedit',
    'Gread', 'Gwrite', 'Gwq', 'Gdiff', 'Gsdiff', 'Gvdiff',
    'Gmove', 'Gremove', 'Gblame', 'Gbrowse',
]

# [[plugins]]
# repo = 'tpope/vim-surround'
#. }}}

#. toml:se fdm=marker:
