#. Common {{{
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

  [plugins.build]
  windows = 'tools\\update-dll-mingw'
  cygwin  = 'make -f make_cygwin.mak'
  mac     = 'make -f make_mac.mak'
  linux   = 'make'
  unix    = 'gmake'
#. }}}

#. Edit plugins {{{
[[plugins]]
repo = 'thinca/vim-zenspace'
hook_add = '''
  au MyAutoCmd ColorScheme * highlight ZenSpace ctermfg=LightGray guibg=DarkGray
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
#. }}}

#. toml:se fdm=marker:
