nocolor = true
nogroup = true
smart-case = true
hidden = true
vcs-ignore = ['.gitignore','.git/info/exclude', '.hgignore_global', '.hgignore']
ignore = ['.git', '.svn', '.hg', '.exe', '*tags', '.pyc', '.DS_Store', '*venv*', '.idea', '.tox', '.orig', '*bak*', '*.mypy_cache', 'node_modules']

# vim: ft=config
